# logger options
image_save_iter: 20000       # How often do you want to save output images during training
image_display_iter: 5000       # How often do you want to display output images during training
snapshot_save_iter: 5000      # How often do you want to save trained models
log_iter: 10                   # How often do you want to log the training stats

# optimization options
max_iter: 250000              # maximum number of training iterations
weight_decay: 0.0001          # weight decay
lr: 0.0001                # learning rate for the generator
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
rec_6d_w: 1
rec_rot_w: 1
rec_pose_w: 10
rec_joint_pos_w: 0
rec_root_v_w: 0
rec_linear_v_w: 0
rec_angular_v_w: 0
kl_w: 0.003
shallow_kl_w: 0.003
pre_kl_w: 0.0003
validation_iter: 500

iteration_interval: 50000
fade_in_duration: 40000

lr_policy: step
step_size: 100000
gamma: 0.3

# model options
model_name: TwoHierSAVAEModel
batch_size: 8
latent_d: 24
shallow_latent_d: 12
n_joints: 22
input_dim: 6
output_dim: 6      

num_layers: 4          
skeleton_dist: 2
skeleton_pool: mean
extra_conv: 0
padding_mode: reflection
kernel_size: 15
upsampling: linear

fps_aug_flag: False
lr_flip_flag: False
random_root_rot_flag: False

use_30fps_data: True
train_5s_model: True
train_10s_model: False
train_salsa_data: False

train_seq_len: 64
input_joint_pos: False
input_root_v: False
input_linear_v: False
input_angular_v: False 
max_input_timesteps: 300

use_shallow_model: True
hier_use_add: False


# For motion temporal interpolation 
opt_lr: 0.1
opt_it: 150

reg_w: 0
reg_w_decoder: 1000
reg_w_trajectory: 0

opt_lr_policy: step 
opt_step_size: 50
opt_gamma: 0.1

interpolation_window: 5

optimize_decoder: True
optimize_trajectory: False
replace_frame_with_gt: True